// sal.h stub for Linux - Source Annotation Language
// Comprehensive SAL annotation definitions
#pragma once

// Basic SAL annotations
#define _In_
#define _Out_
#define _Inout_
#define _In_z_
#define _In_opt_
#define _In_opt_z_
#define _Out_opt_
#define _Out_writes_(x)
#define _Out_writes_bytes_(x)
#define _Out_writes_z_(x)
#define _Out_writes_opt_(x)
#define _Out_writes_to_(s,c)
#define _Out_writes_bytes_to_(s,c)
#define _In_reads_(x)
#define _In_reads_bytes_(x)
#define _In_reads_z_(x)
#define _In_reads_opt_(x)
#define _In_reads_opt_z_(x)
#define _In_reads_to_(x,y)
#define _Inout_updates_(x)
#define _Inout_updates_bytes_(x)
#define _Inout_updates_z_(x)
#define _Outptr_
#define _Outptr_result_maybenull_
#define _Outptr_opt_
#define _Outptr_opt_result_maybenull_
#define _COM_Outptr_
#define _COM_Outptr_result_maybenull_
#define _Outptr_result_buffer_(x)
#define _Outptr_result_bytebuffer_(x)
#define _Printf_format_string_
#define _Success_(x)
#define _Field_size_(x)
#define _Field_size_bytes_(x)
#define _Field_size_opt_(x)
#define _Field_size_part_(x,y)
#define _Analysis_assume_(x)
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Ret_z_
#define _Post_writable_byte_size_(x)
#define _Post_z_
#define DECLSPEC_SELECTANY
#define _Use_decl_annotations_
#define _Check_return_
#define _IRQL_requires_same_
#define _Post_equal_to_(x)
#define _Pre_defensive_
#define _Post_defensive_
#define _On_failure_(x)
#define _Always_(x)
#define _Maybenull_
#define _Notnull_
#define _Null_terminated_
#define _NullNull_terminated_
#define _Pre_maybenull_
#define _Pre_notnull_
#define _Pre_valid_
#define _Post_maybenull_
#define _Post_notnull_
#define _Post_valid_
#define _Readable_bytes_(x)
#define _Readable_elements_(x)
#define _Writable_bytes_(x)
#define _Writable_elements_(x)
#define _Pre_z_
#define _Pre_writable_size_(x)
#define _Pre_readable_size_(x)
#define _Post_bytecap_(x)
#define _Post_bytecount_(x)
#define _Benign_race_begin_
#define _Benign_race_end_
#define _No_competing_thread_
#define _Acquires_lock_(x)
#define _Releases_lock_(x)
#define _Requires_lock_held_(x)
#define _Requires_lock_not_held_(x)
#define _Interlocked_
#define _Has_lock_kind_(x)
#define _Lock_level_order_(x,y)
#define _Create_lock_level_(x)
#define _Function_class_(x)
#define _Raises_SEH_exception_
#define _Maybe_raises_SEH_exception_
#define _Acquires_shared_lock_(x)
#define _Releases_shared_lock_(x)
#define _Requires_shared_lock_held_(x)
#define _Analysis_mode_(x)
#define _Strict_type_match_
#define _Dispatch_type_(x)
#define _Enum_is_bitflag_
#define _Points_to_data_
#define _Literal_
#define _Notliteral_
#define _Pre_satisfies_(x)
#define _Post_satisfies_(x)
#define _When_(x)
#define _At_(x,y)
#define _At_buffer_(x,y)
#define _Group_(x)
#define _Group_impl_(x)
#define _Analysis_noreturn_
#define _Unreferenced_parameter_
#define _Post_
#define _Pre_
#define _Deref_pre_
#define _Deref_post_
#define _Deref_inout_
#define _Deref_out_
#define _Deref_opt_out_
#define _Deref_out_opt_
#define _Deref_pre_z_
#define _Deref_post_z_
#define _Deref_out_z_
#define _Deref_pre_cap_(x)
#define _Deref_post_cap_(x)
#define _Deref_pre_bytecap_(x)
#define _Deref_post_bytecap_(x)
#define _Deref_pre_valid_
#define _Deref_post_valid_
#define _Deref_pre_maybenull_
#define _Deref_post_maybenull_
#define _Deref_pre_notnull_
#define _Deref_post_notnull_
#define _Deref_pre_readonly_
#define _Deref_post_readonly_
#define _Outptr_result_nullonfailure_
#define _Outptr_result_buffer_maybenull_(x)
#define _Out_writes_to_ptr_(x)
#define _Out_writes_to_ptr_z_(x)
#define _In_range_(lb,ub)
#define _Out_range_(lb,ub)
#define _Ret_range_(lb,ub)
#define _Deref_out_range_(lb,ub)
#define _Pre_equal_to_(x)
#define _Struct_size_bytes_(x)
